export const result = [
  {
    jobUrl: "https://de.indeed.com/viewjob?jk=a4edceaebf6d8b96",
    requiredLanguages: ["Kotlin", "Java", "JavaScript", "TypeScript", "SQL"],
    requiredFrameworks: ["Vue"],
    isConsulting: false,
    companySize: "10,000+",
  },
  {
    jobUrl: "https://de.indeed.com/viewjob?jk=5ff9d4926bca641b",
    requiredLanguages: ["Java", "JavaScript", "TypeScript", "SQL"],
    requiredFrameworks: ["Angular"],
    isConsulting: false,
    companySize: "201 to 500",
  },
  {
    jobUrl: "https://de.indeed.com/viewjob?jk=a7bf7b02ed40bb89",
    requiredLanguages: ["Python", "SQL", "Java"],
    requiredFrameworks: [],
    isConsulting: false,
    companySize: "5,001 to 10,000",
  },
  {
    jobUrl: "https://de.indeed.com/viewjob?jk=82b605408bb884eb",
    requiredLanguages: ["Java", "JavaScript", "TypeScript", "SQL"],
    requiredFrameworks: [],
    isConsulting: false,
    companySize: "10,000+",
  },
  {
    jobUrl: "https://de.indeed.com/viewjob?jk=fa38edfc723addd4",
    requiredLanguages: ["Java", "Kotlin", "TypeScript", "JavaScript", "SQL"],
    requiredFrameworks: ["React"],
    isConsulting: false,
    companySize: "",
  },
  {
    jobUrl: "https://de.indeed.com/viewjob?jk=76926e1fdba9188e",
    requiredLanguages: ["Java", "TypeScript", "SQL"],
    requiredFrameworks: ["React"],
    isConsulting: false,
    companySize: "",
  },
  {
    jobUrl: "https://de.indeed.com/viewjob?jk=7a33540fc0da0f2a",
    requiredLanguages: ["Java", "TypeScript"],
    requiredFrameworks: ["React", "Angular", "Vue"],
    isConsulting: false,
    companySize: "2 to 10",
  },
  {
    jobUrl: "https://de.indeed.com/viewjob?jk=c9643a2fbad14070",
    requiredLanguages: ["C#"],
    requiredFrameworks: [],
    isConsulting: true,
    companySize: "11 to 50",
  },
  {
    jobUrl: "https://de.indeed.com/viewjob?jk=1a27169352a0c8a2",
    requiredLanguages: ["Java", "TypeScript", "SQL"],
    requiredFrameworks: ["Vue"],
    isConsulting: false,
    companySize: "",
  },
  {
    jobUrl: "https://de.indeed.com/viewjob?jk=64ce71a7c77e8dac",
    requiredLanguages: ["TypeScript"],
    requiredFrameworks: ["React", "Vue"],
    isConsulting: false,
    companySize: "",
  },
  {
    jobUrl: "https://de.indeed.com/viewjob?jk=a36a0d15e8d56072",
    requiredLanguages: [],
    requiredFrameworks: [],
    isConsulting: false,
    companySize: "51 to 200",
  },
  {
    jobUrl: "https://de.indeed.com/viewjob?jk=0e3c7d474e3ffe7f",
    requiredLanguages: ["JavaScript"],
    requiredFrameworks: [],
    isConsulting: false,
    companySize: "",
  },
  {
    jobUrl: "https://de.indeed.com/viewjob?jk=e9b4cf691074d3ed",
    requiredLanguages: ["C++", "C#", "C"],
    requiredFrameworks: [],
    isConsulting: false,
    companySize: "",
  },
  {
    jobUrl: "https://de.indeed.com/viewjob?jk=8c3ed7c1e9c32f61",
    requiredLanguages: ["Java", "JavaScript"],
    requiredFrameworks: [],
    isConsulting: false,
    companySize: "10,000+",
  },
  {
    jobUrl: "https://de.indeed.com/viewjob?jk=e49c42b520007705",
    requiredLanguages: [],
    requiredFrameworks: [],
    isConsulting: false,
    companySize: "",
  },
  {
    jobUrl: "https://de.indeed.com/viewjob?jk=c1a0830c00da5fb0",
    requiredLanguages: [],
    requiredFrameworks: [],
    isConsulting: false,
    companySize: "",
  },
  {
    jobUrl: "https://de.indeed.com/viewjob?jk=4b47e5cf136bc463",
    requiredLanguages: ["SQL"],
    requiredFrameworks: [],
    isConsulting: true,
    companySize: "51 to 200",
  },
  {
    jobUrl: "https://de.indeed.com/viewjob?jk=f6af71c43324fb55",
    requiredLanguages: ["Java", "Go", "SQL"],
    requiredFrameworks: [],
    isConsulting: false,
    companySize: "10,000+",
  },
  {
    jobUrl: "https://de.indeed.com/viewjob?jk=24c5499b2b4fc0d5",
    requiredLanguages: ["JavaScript", "Python", "TypeScript", "SQL"],
    requiredFrameworks: ["React"],
    isConsulting: false,
    companySize: "5,001 to 10,000",
  },
  {
    jobUrl: "https://de.indeed.com/viewjob?jk=c698b7bb916761ea",
    requiredLanguages: [],
    requiredFrameworks: [],
    isConsulting: false,
    companySize: "",
  },
  {
    jobUrl: "https://de.indeed.com/viewjob?jk=aeeecdd00e190d2b",
    requiredLanguages: ["C++"],
    requiredFrameworks: [],
    isConsulting: false,
    companySize: "",
  },
  {
    jobUrl: "https://de.indeed.com/viewjob?jk=af0f351dfd744745",
    requiredLanguages: [],
    requiredFrameworks: [],
    isConsulting: false,
    companySize: "",
  },
  {
    jobUrl: "https://de.indeed.com/viewjob?jk=016f3f820a942007",
    requiredLanguages: ["C#", "Python"],
    requiredFrameworks: [],
    isConsulting: false,
    companySize: "201 to 500",
  },
  {
    jobUrl: "https://de.indeed.com/viewjob?jk=b6b935e34baf61b6",
    requiredLanguages: ["Java"],
    requiredFrameworks: [],
    isConsulting: false,
    companySize: "10,000+",
  },
  {
    jobUrl: "https://de.indeed.com/viewjob?jk=2706d65694bced70",
    requiredLanguages: ["JavaScript", "TypeScript"],
    requiredFrameworks: ["React"],
    isConsulting: false,
    companySize: "51 to 200",
  },
  {
    jobUrl: "https://de.indeed.com/viewjob?jk=1dba904c8368ac1b",
    requiredLanguages: ["Python", "Go", "SQL"],
    requiredFrameworks: [],
    isConsulting: false,
    companySize: "",
  },
  {
    jobUrl: "https://de.indeed.com/viewjob?jk=00bd7901fd6918fe",
    requiredLanguages: [],
    requiredFrameworks: [],
    isConsulting: false,
    companySize: "201 to 500",
  },
  {
    jobUrl: "https://de.indeed.com/viewjob?jk=b052ade38dc4b64b",
    requiredLanguages: ["JavaScript", "C#", "SQL", "TypeScript"],
    requiredFrameworks: [],
    isConsulting: false,
    companySize: "11 to 50",
  },
  {
    jobUrl: "https://de.indeed.com/viewjob?jk=3f3dd9b2671dcb15",
    requiredLanguages: ["JavaScript", "TypeScript", "SQL"],
    requiredFrameworks: ["React"],
    isConsulting: false,
    companySize: "",
  },
  {
    jobUrl: "https://de.indeed.com/viewjob?jk=e26eb053ae18fcdf",
    requiredLanguages: ["TypeScript", "C#"],
    requiredFrameworks: ["Angular", "React", "Vue"],
    isConsulting: true,
    companySize: "11 to 50",
  },
  {
    jobUrl: "https://de.indeed.com/viewjob?jk=873e66c398a0ab77",
    requiredLanguages: ["Java"],
    requiredFrameworks: [],
    isConsulting: true,
    companySize: "10,000+",
  },
  {
    jobUrl: "https://de.indeed.com/viewjob?jk=d0c2e9ff8b5e8707",
    requiredLanguages: ["Python", "TypeScript", "SQL"],
    requiredFrameworks: ["React"],
    isConsulting: false,
    companySize: "",
  },
  {
    jobUrl: "https://de.indeed.com/viewjob?jk=087cfe7e079ea52c",
    requiredLanguages: ["Go"],
    requiredFrameworks: [],
    isConsulting: false,
    companySize: "",
  },
  {
    jobUrl: "https://de.indeed.com/viewjob?jk=9685d2c2f85da48e",
    requiredLanguages: ["Ruby", "SQL"],
    requiredFrameworks: [],
    isConsulting: false,
    companySize: "",
  },
  {
    jobUrl: "https://de.indeed.com/viewjob?jk=9d55f4718a8519af",
    requiredLanguages: ["C++", "Python", "Java"],
    requiredFrameworks: [],
    isConsulting: true,
    companySize: "",
  },
  {
    jobUrl: "https://de.indeed.com/viewjob?jk=766eba9053665b44",
    requiredLanguages: ["Scala", "Java", "Python", "JavaScript", "SQL"],
    requiredFrameworks: ["Vue"],
    isConsulting: false,
    companySize: "10,000+",
  },
  {
    jobUrl: "https://de.indeed.com/viewjob?jk=21e7ca245fb3e380",
    requiredLanguages: ["Java", "Kotlin"],
    requiredFrameworks: [],
    isConsulting: false,
    companySize: "51 to 200",
  },
  {
    jobUrl: "https://de.indeed.com/viewjob?jk=beb3ad74a22aaed3",
    requiredLanguages: ["Swift"],
    requiredFrameworks: [],
    isConsulting: false,
    companySize: "1 to 50",
  },
  {
    jobUrl: "https://de.indeed.com/viewjob?jk=e991980ac16fe2cc",
    requiredLanguages: ["Python", "Go", "Rust"],
    requiredFrameworks: [],
    isConsulting: false,
    companySize: "11 to 50",
  },
  {
    jobUrl: "https://de.indeed.com/viewjob?jk=7dcffcd775a8a26c",
    requiredLanguages: ["Python", "Golang", "Rust"],
    requiredFrameworks: [],
    isConsulting: false,
    companySize: "51 to 200",
  },
  {
    jobUrl: "https://de.indeed.com/viewjob?jk=4646f38eab4012bf",
    requiredLanguages: ["Go", "Golang"],
    requiredFrameworks: [],
    isConsulting: false,
    companySize: "51 to 200",
  },
  {
    jobUrl: "https://de.indeed.com/viewjob?jk=e401f39fe9f33deb",
    requiredLanguages: ["JavaScript", "SQL"],
    requiredFrameworks: ["Angular"],
    isConsulting: false,
    companySize: "501 to 1,000",
  },
  {
    jobUrl: "https://de.indeed.com/viewjob?jk=0b88227773c15f19",
    requiredLanguages: ["TypeScript"],
    requiredFrameworks: ["React", "Angular"],
    isConsulting: true,
    companySize: "10,000+",
  },
  {
    jobUrl: "https://de.indeed.com/viewjob?jk=2798b82e1fc7fa3c",
    requiredLanguages: ["C#", "Java", "C++", "SQL"],
    requiredFrameworks: [],
    isConsulting: false,
    companySize: "",
  },
  {
    jobUrl: "https://de.indeed.com/viewjob?jk=0e4de68dece6c8c0",
    requiredLanguages: [],
    requiredFrameworks: [],
    isConsulting: false,
    companySize: "",
  },
  {
    jobUrl: "https://de.indeed.com/viewjob?jk=5d0192be9a36c314",
    requiredLanguages: ["Rust", "Go", "TypeScript"],
    requiredFrameworks: [],
    isConsulting: false,
    companySize: "201 to 500",
  },
  {
    jobUrl: "https://de.indeed.com/viewjob?jk=94c1b8c669c22d1f",
    requiredLanguages: ["C#"],
    requiredFrameworks: [],
    isConsulting: true,
    companySize: "201 to 500",
  },
  {
    jobUrl: "https://de.indeed.com/viewjob?jk=a2406d5bac235573",
    requiredLanguages: ["C#"],
    requiredFrameworks: [],
    isConsulting: true,
    companySize: "201 to 500",
  },
  {
    jobUrl: "https://de.indeed.com/viewjob?jk=f61ed8df1b5c631c",
    requiredLanguages: ["C#", "JavaScript", "Java", "SQL"],
    requiredFrameworks: [],
    isConsulting: false,
    companySize: "",
  },
  {
    jobUrl: "https://de.indeed.com/viewjob?jk=f528b18498703f20",
    requiredLanguages: ["Java", "SQL"],
    requiredFrameworks: [],
    isConsulting: false,
    companySize: "5,001 to 10,000",
  },
  {
    jobUrl: "https://de.indeed.com/viewjob?jk=ab9c5064caaafee0",
    requiredLanguages: ["C++"],
    requiredFrameworks: [],
    isConsulting: false,
    companySize: "",
  },
  {
    jobUrl: "https://de.indeed.com/viewjob?jk=810a324d11743267",
    requiredLanguages: ["SAP"],
    requiredFrameworks: [],
    isConsulting: false,
    companySize: "",
  },
  {
    jobUrl: "https://de.indeed.com/viewjob?jk=c8438eef345985dd",
    requiredLanguages: ["Swift"],
    requiredFrameworks: [],
    isConsulting: false,
    companySize: "",
  },
  {
    jobUrl: "https://de.indeed.com/viewjob?jk=a9febe98413e03b7",
    requiredLanguages: ["JavaScript", "Java"],
    requiredFrameworks: [],
    isConsulting: false,
    companySize: "5,001 to 10,000",
  },
  {
    jobUrl: "https://de.indeed.com/viewjob?jk=95d051fc0d89afa9",
    requiredLanguages: ["JavaScript", "TypeScript"],
    requiredFrameworks: ["React", "Angular", "Vue"],
    isConsulting: false,
    companySize: "10,000+",
  },
  {
    jobUrl: "https://de.indeed.com/viewjob?jk=47c55a542f110cbd",
    requiredLanguages: ["JavaScript", "TypeScript"],
    requiredFrameworks: ["Vue"],
    isConsulting: false,
    companySize: "",
  },
  {
    jobUrl: "https://de.indeed.com/viewjob?jk=3edf34853e2308bd",
    requiredLanguages: ["C#", "PHP"],
    requiredFrameworks: [],
    isConsulting: false,
    companySize: "501 to 1,000",
  },
  {
    jobUrl: "https://de.indeed.com/viewjob?jk=2d2efd24f78507a8",
    requiredLanguages: ["JavaScript", "Java"],
    requiredFrameworks: [],
    isConsulting: false,
    companySize: "5,001 to 10,000",
  },
  {
    jobUrl: "https://de.indeed.com/viewjob?jk=32b3e4d9b1d1735d",
    requiredLanguages: ["C#", "TypeScript", "SQL", "Kotlin"],
    requiredFrameworks: [],
    isConsulting: false,
    companySize: "",
  },
  {
    jobUrl: "https://de.indeed.com/viewjob?jk=f79e1e9dc4c5e6f8",
    requiredLanguages: ["C#", "SQL"],
    requiredFrameworks: [],
    isConsulting: false,
    companySize: "201 to 500",
  },
  {
    jobUrl: "https://de.indeed.com/viewjob?jk=da41b29485388d23",
    requiredLanguages: ["JavaScript", "TypeScript"],
    requiredFrameworks: ["React"],
    isConsulting: false,
    companySize: "",
  },
  {
    jobUrl: "https://de.indeed.com/viewjob?jk=c8756b557c376fdc",
    requiredLanguages: ["TypeScript", "SQL"],
    requiredFrameworks: ["React"],
    isConsulting: false,
    companySize: "",
  },
  {
    jobUrl: "https://de.indeed.com/viewjob?jk=d6e494a922830405",
    requiredLanguages: ["C", "C++", "C#", "Pascal"],
    requiredFrameworks: [],
    isConsulting: false,
    companySize: "",
  },
  {
    jobUrl: "https://de.indeed.com/viewjob?jk=7445aa9dd0279922",
    requiredLanguages: ["C#"],
    requiredFrameworks: [],
    isConsulting: true,
    companySize: "1,001 to 5,000",
  },
  {
    jobUrl: "https://de.indeed.com/viewjob?jk=306029ca9537cc9f",
    requiredLanguages: ["Java"],
    requiredFrameworks: [],
    isConsulting: false,
    companySize: "10,000+",
  },
  {
    jobUrl: "https://de.indeed.com/viewjob?jk=d063120aad6f8179",
    requiredLanguages: ["C++", "C#"],
    requiredFrameworks: [],
    isConsulting: false,
    companySize: "51 to 200",
  },
  {
    jobUrl: "https://de.indeed.com/viewjob?jk=377c041bea3f7387",
    requiredLanguages: ["Ruby", "TypeScript", "SQL"],
    requiredFrameworks: ["Vue"],
    isConsulting: false,
    companySize: "",
  },
  {
    jobUrl: "https://de.indeed.com/viewjob?jk=78090a85723c9cec",
    requiredLanguages: [],
    requiredFrameworks: [],
    isConsulting: true,
    companySize: "",
  },
  {
    jobUrl: "https://de.indeed.com/viewjob?jk=acf8b4ac68dfdc4d",
    requiredLanguages: ["JavaScript", "TypeScript"],
    requiredFrameworks: ["React", "Angular", "Vue"],
    isConsulting: true,
    companySize: "",
  },
  {
    jobUrl: "https://de.indeed.com/viewjob?jk=38c66eff1b1efc0a",
    requiredLanguages: ["Java", "SQL"],
    requiredFrameworks: [],
    isConsulting: true,
    companySize: "",
  },
  {
    jobUrl: "https://de.indeed.com/viewjob?jk=f8492a6750a869b9",
    requiredLanguages: ["C#"],
    requiredFrameworks: [],
    isConsulting: false,
    companySize: "",
  },
  {
    jobUrl: "https://de.indeed.com/viewjob?jk=05b156d5dcb12595",
    requiredLanguages: ["C#", "Java", "SQL"],
    requiredFrameworks: [],
    isConsulting: false,
    companySize: "",
  },
  {
    jobUrl: "https://de.indeed.com/viewjob?jk=80560aa58de4ab2f",
    requiredLanguages: ["Kotlin", "TypeScript"],
    requiredFrameworks: ["Angular"],
    isConsulting: false,
    companySize: "1,001 to 5,000",
  },
  {
    jobUrl: "https://de.indeed.com/viewjob?jk=a2427d174b9e479c",
    requiredLanguages: ["JavaScript"],
    requiredFrameworks: [],
    isConsulting: false,
    companySize: "",
  },
  {
    jobUrl: "https://de.indeed.com/viewjob?jk=b8ec16e9ddd9a0f0",
    requiredLanguages: ["C++", "C", "Python", "JavaScript"],
    requiredFrameworks: [],
    isConsulting: false,
    companySize: "",
  },
  {
    jobUrl: "https://de.indeed.com/viewjob?jk=0d5981e2ba4f0080",
    requiredLanguages: ["JavaScript", "TypeScript", "SQL"],
    requiredFrameworks: ["Vue"],
    isConsulting: false,
    companySize: "",
  },
  {
    jobUrl: "https://de.indeed.com/viewjob?jk=ab29a2cf544e9f58",
    requiredLanguages: ["TypeScript", "SQL"],
    requiredFrameworks: [],
    isConsulting: false,
    companySize: "5,001 to 10,000",
  },
  {
    jobUrl: "https://de.indeed.com/viewjob?jk=7769ad94875225c4",
    requiredLanguages: ["C#", "JavaScript", "SQL"],
    requiredFrameworks: ["Angular"],
    isConsulting: false,
    companySize: "501 to 1,000",
  },
  {
    jobUrl: "https://de.indeed.com/viewjob?jk=b3e4f71b6e7ec23c",
    requiredLanguages: ["C#", "TypeScript"],
    requiredFrameworks: ["React"],
    isConsulting: false,
    companySize: "1,001 to 5,000",
  },
  {
    jobUrl: "https://de.indeed.com/viewjob?jk=ecd06b0dfb37d2a0",
    requiredLanguages: ["SAP"],
    requiredFrameworks: [],
    isConsulting: true,
    companySize: "",
  },
  {
    jobUrl: "https://de.indeed.com/viewjob?jk=42b4f37da5f0aee6",
    requiredLanguages: ["Python", "JavaScript"],
    requiredFrameworks: ["React"],
    isConsulting: false,
    companySize: "",
  },
  {
    jobUrl: "https://de.indeed.com/viewjob?jk=d4f0870c38747ef4",
    requiredLanguages: ["Python", "JavaScript", "TypeScript"],
    requiredFrameworks: ["React"],
    isConsulting: false,
    companySize: "",
  },
  {
    jobUrl: "https://de.indeed.com/viewjob?jk=dfbfa2366abf4c10",
    requiredLanguages: ["Go", "SQL"],
    requiredFrameworks: [],
    isConsulting: false,
    companySize: "1,001 to 5,000",
  },
  {
    jobUrl: "https://de.indeed.com/viewjob?jk=ee8d101253497e5e",
    requiredLanguages: ["Go", "Python", "Rust"],
    requiredFrameworks: [],
    isConsulting: false,
    companySize: "51 to 200",
  },
  {
    jobUrl: "https://de.indeed.com/viewjob?jk=33b2746ba06cb42f",
    requiredLanguages: ["JavaScript", "PHP", "C++"],
    requiredFrameworks: [],
    isConsulting: false,
    companySize: "11 to 50",
  },
  {
    jobUrl: "https://de.indeed.com/viewjob?jk=1b0dfdacfed21772",
    requiredLanguages: ["Python"],
    requiredFrameworks: [],
    isConsulting: false,
    companySize: "1,001 to 5,000",
  },
  {
    jobUrl: "https://de.indeed.com/viewjob?jk=6e2caa16452cb6cd",
    requiredLanguages: ["Scala"],
    requiredFrameworks: [],
    isConsulting: false,
    companySize: "",
  },
  {
    jobUrl: "https://de.indeed.com/viewjob?jk=54942e5fe2aeb487",
    requiredLanguages: ["Scala"],
    requiredFrameworks: [],
    isConsulting: false,
    companySize: "",
  },
  {
    jobUrl: "https://de.indeed.com/viewjob?jk=d39182e6b7b9df5b",
    requiredLanguages: ["Java", "C#"],
    requiredFrameworks: [],
    isConsulting: false,
    companySize: "201 to 500",
  },
  {
    jobUrl: "https://de.indeed.com/viewjob?jk=0628d65f1d2240e7",
    requiredLanguages: ["C#"],
    requiredFrameworks: ["Vue", "Angular", "Svelte"],
    isConsulting: true,
    companySize: "",
  },
  {
    jobUrl: "https://de.indeed.com/viewjob?jk=3b0d06900789634d",
    requiredLanguages: ["JavaScript", "Java"],
    requiredFrameworks: ["React"],
    isConsulting: false,
    companySize: "",
  },
  {
    jobUrl: "https://de.indeed.com/viewjob?jk=7860e7ab5912a2dc",
    requiredLanguages: ["Python", "C++"],
    requiredFrameworks: [],
    isConsulting: false,
    companySize: "",
  },
  {
    jobUrl: "https://de.indeed.com/viewjob?jk=3b8daf901e1e4dde",
    requiredLanguages: [],
    requiredFrameworks: [],
    isConsulting: false,
    companySize: "",
  },
  {
    jobUrl: "https://de.indeed.com/viewjob?jk=9c61351f365f00bc",
    requiredLanguages: ["Java"],
    requiredFrameworks: [],
    isConsulting: false,
    companySize: "",
  },
  {
    jobUrl: "https://de.indeed.com/viewjob?jk=563d5af2c8ed3c5e",
    requiredLanguages: ["Python", "Java", "C++", "C#", "SQL"],
    requiredFrameworks: [],
    isConsulting: true,
    companySize: "1,001 to 5,000",
  },
  {
    jobUrl: "https://de.indeed.com/viewjob?jk=933e054a5c837678",
    requiredLanguages: ["TypeScript", "SQL"],
    requiredFrameworks: ["React"],
    isConsulting: false,
    companySize: "",
  },
  {
    jobUrl: "https://de.indeed.com/viewjob?jk=cef831bdef8d3b71",
    requiredLanguages: ["Java", "TypeScript"],
    requiredFrameworks: [],
    isConsulting: false,
    companySize: "5,001 to 10,000",
  },
  {
    jobUrl: "https://de.indeed.com/viewjob?jk=50ec11af50e9d960",
    requiredLanguages: ["C#"],
    requiredFrameworks: [],
    isConsulting: false,
    companySize: "",
  },
  {
    jobUrl: "https://de.indeed.com/viewjob?jk=cbfa728ad4267635",
    requiredLanguages: ["C#"],
    requiredFrameworks: [],
    isConsulting: false,
    companySize: "51 to 200",
  },
  {
    jobUrl: "https://de.indeed.com/viewjob?jk=3411465a2ed506b8",
    requiredLanguages: ["Swift", "Java"],
    requiredFrameworks: ["Angular", "React"],
    isConsulting: true,
    companySize: "10,000+",
  },
  {
    jobUrl: "https://de.indeed.com/viewjob?jk=7fd9209e6b18b603",
    requiredLanguages: ["Go", "Java", "PHP", "Python", "JavaScript"],
    requiredFrameworks: ["React", "Angular", "Svelte"],
    isConsulting: false,
    companySize: "51 to 200",
  },
  {
    jobUrl: "https://de.indeed.com/viewjob?jk=93434cd9a0322cd7",
    requiredLanguages: ["Go", "Java", "PHP", "Python", "JavaScript"],
    requiredFrameworks: ["React", "Angular", "Svelte"],
    isConsulting: false,
    companySize: "",
  },
  {
    jobUrl: "https://de.indeed.com/viewjob?jk=c4212f5ea4a190e2",
    requiredLanguages: ["JavaScript", "C#", "SQL"],
    requiredFrameworks: ["React", "Angular"],
    isConsulting: false,
    companySize: "5,001 to 10,000",
  },
  {
    jobUrl: "https://de.indeed.com/viewjob?jk=485636c118220e80",
    requiredLanguages: ["Swift", "Java", "Kotlin"],
    requiredFrameworks: [],
    isConsulting: false,
    companySize: "11 to 50",
  },
  {
    jobUrl: "https://de.indeed.com/viewjob?jk=71b05ce01f688bdf",
    requiredLanguages: ["Swift", "Java", "Kotlin"],
    requiredFrameworks: [],
    isConsulting: false,
    companySize: "51 to 200",
  },
  {
    jobUrl: "https://de.indeed.com/viewjob?jk=a0e81409b7df7b58",
    requiredLanguages: [],
    requiredFrameworks: [],
    isConsulting: false,
    companySize: "10,000+",
  },
  {
    jobUrl: "https://de.indeed.com/viewjob?jk=34826a172f9953ee",
    requiredLanguages: ["Java", "SAP"],
    requiredFrameworks: [],
    isConsulting: false,
    companySize: "10,000+",
  },
  {
    jobUrl: "https://de.indeed.com/viewjob?jk=127db63987e6f033",
    requiredLanguages: ["PHP", "JavaScript", "SQL"],
    requiredFrameworks: [],
    isConsulting: false,
    companySize: "",
  },
  {
    jobUrl: "https://de.indeed.com/viewjob?jk=b1b48835331d3579",
    requiredLanguages: ["Java", "Kotlin"],
    requiredFrameworks: [],
    isConsulting: false,
    companySize: "",
  },
  {
    jobUrl: "https://de.indeed.com/viewjob?jk=a850bc5ff3c0ed83",
    requiredLanguages: ["Java", "C#", "TypeScript", "JavaScript"],
    requiredFrameworks: ["Angular", "React", "Vue"],
    isConsulting: false,
    companySize: "",
  },
  {
    jobUrl: "https://de.indeed.com/viewjob?jk=dea020ce772137c0",
    requiredLanguages: ["C#", "Visual Basic .NET", "SQL"],
    requiredFrameworks: [],
    isConsulting: false,
    companySize: "51 to 200",
  },
  {
    jobUrl: "https://de.indeed.com/viewjob?jk=ab1fc1d682b10f1d",
    requiredLanguages: ["C#"],
    requiredFrameworks: [],
    isConsulting: true,
    companySize: "11 to 50",
  },
  {
    jobUrl: "https://de.indeed.com/viewjob?jk=586e35a1aa09460c",
    requiredLanguages: ["C++", "C#", "C"],
    requiredFrameworks: [],
    isConsulting: false,
    companySize: "",
  },
  {
    jobUrl: "https://de.indeed.com/viewjob?jk=36d982229d356844",
    requiredLanguages: ["Ruby"],
    requiredFrameworks: [],
    isConsulting: false,
    companySize: "",
  },
  {
    jobUrl: "https://de.indeed.com/viewjob?jk=f0750d0d4c2687e8",
    requiredLanguages: ["Swift"],
    requiredFrameworks: [],
    isConsulting: false,
    companySize: "1 to 50",
  },
  {
    jobUrl: "https://de.indeed.com/viewjob?jk=7e784bdd207649f0",
    requiredLanguages: ["Kotlin", "Swift"],
    requiredFrameworks: ["React"],
    isConsulting: false,
    companySize: "501 to 1,000",
  },
  {
    jobUrl: "https://de.indeed.com/viewjob?jk=619039c96df81c52",
    requiredLanguages: ["Kotlin"],
    requiredFrameworks: [],
    isConsulting: false,
    companySize: "501 to 1,000",
  },
  {
    jobUrl: "https://de.indeed.com/viewjob?jk=e19f81f61427c14e",
    requiredLanguages: ["Java"],
    requiredFrameworks: ["Angular"],
    isConsulting: false,
    companySize: "",
  },
  {
    jobUrl: "https://de.indeed.com/viewjob?jk=52dc0a2f6f8c634f",
    requiredLanguages: ["JavaScript", "TypeScript"],
    requiredFrameworks: [],
    isConsulting: false,
    companySize: "1,001 to 5,000",
  },
  {
    jobUrl: "https://de.indeed.com/viewjob?jk=c71790844243247b",
    requiredLanguages: ["Java", "TypeScript", "JavaScript", "SQL"],
    requiredFrameworks: ["React", "Angular", "Vue"],
    isConsulting: true,
    companySize: "51 to 200",
  },
  {
    jobUrl: "https://de.indeed.com/viewjob?jk=bb9a3d262e9b3947",
    requiredLanguages: ["JavaScript", "Python", "Java", "TypeScript", "Perl"],
    requiredFrameworks: ["React", "Angular"],
    isConsulting: true,
    companySize: "51 to 200",
  },
  {
    jobUrl: "https://de.indeed.com/viewjob?jk=82a495caf56e17b1",
    requiredLanguages: ["JavaScript", "PHP"],
    requiredFrameworks: [],
    isConsulting: true,
    companySize: "2 to 10",
  },
  {
    jobUrl: "https://de.indeed.com/viewjob?jk=a9d4ff31d5d28e5f",
    requiredLanguages: ["JavaScript", "PHP"],
    requiredFrameworks: ["Vue", "React"],
    isConsulting: true,
    companySize: "2 to 10",
  },
  {
    jobUrl: "https://de.indeed.com/viewjob?jk=4c70149c7ed94812",
    requiredLanguages: ["JavaScript"],
    requiredFrameworks: [],
    isConsulting: false,
    companySize: "",
  },
  {
    jobUrl: "https://de.indeed.com/viewjob?jk=2f2af406aa5fc7eb",
    requiredLanguages: ["JavaScript"],
    requiredFrameworks: [
      "Spring Boot",
      "NodeJS",
      "Angular",
      "Vue.js",
      "React",
    ],
    isConsulting: false,
    companySize: "",
  },
  {
    jobUrl: "https://de.indeed.com/viewjob?jk=8c820652941fa931",
    requiredLanguages: [],
    requiredFrameworks: [],
    isConsulting: false,
    companySize: "",
  },
  {
    jobUrl: "https://de.indeed.com/viewjob?jk=1fe9369afea2f66f",
    requiredLanguages: ["JavaScript", "TypeScript"],
    requiredFrameworks: ["Fastify", "Express.js"],
    isConsulting: false,
    companySize: "1 to 50",
  },
  {
    jobUrl: "https://de.indeed.com/viewjob?jk=1bde20ac0a11570f",
    requiredLanguages: ["Kotlin"],
    requiredFrameworks: [],
    isConsulting: false,
    companySize: "1 to 50",
  },
  {
    jobUrl: "https://de.indeed.com/viewjob?jk=cc670aa7122302a3",
    requiredLanguages: ["Go", "TypeScript", "SQL"],
    requiredFrameworks: ["React"],
    isConsulting: false,
    companySize: "51 to 200",
  },
  {
    jobUrl: "https://de.indeed.com/viewjob?jk=f70a35f8d6dcfb5a",
    requiredLanguages: [],
    requiredFrameworks: [],
    isConsulting: false,
    companySize: "",
  },
  {
    jobUrl: "https://de.indeed.com/viewjob?jk=c40781e29ac2356c",
    requiredLanguages: ["Java"],
    requiredFrameworks: [],
    isConsulting: true,
    companySize: "51 to 200",
  },
  {
    jobUrl: "https://de.indeed.com/viewjob?jk=8b64e09334a969f1",
    requiredLanguages: ["Go"],
    requiredFrameworks: [],
    isConsulting: false,
    companySize: "",
  },
  {
    jobUrl: "https://de.indeed.com/viewjob?jk=1cd80dfa64f4fc21",
    requiredLanguages: ["JavaScript", "PHP", "TypeScript"],
    requiredFrameworks: [],
    isConsulting: false,
    companySize: "1,001 to 5,000",
  },
  {
    jobUrl: "https://de.indeed.com/viewjob?jk=3c996aab8b04896c",
    requiredLanguages: ["JavaScript", "PHP", "SQL"],
    requiredFrameworks: ["React", "Vue"],
    isConsulting: false,
    companySize: "11 to 50",
  },
  {
    jobUrl: "https://de.indeed.com/viewjob?jk=06daa29d0cef16c2",
    requiredLanguages: ["PHP"],
    requiredFrameworks: [],
    isConsulting: false,
    companySize: "1,001 to 5,000",
  },
  {
    jobUrl: "https://de.indeed.com/viewjob?jk=a247404a7a8fd33a",
    requiredLanguages: ["TypeScript"],
    requiredFrameworks: ["React", "Angular"],
    isConsulting: false,
    companySize: "1,001 to 5,000",
  },
  {
    jobUrl: "https://de.indeed.com/viewjob?jk=69c7c2d0fce24539",
    requiredLanguages: ["Kotlin"],
    requiredFrameworks: [],
    isConsulting: false,
    companySize: "1,001 to 5,000",
  },
  {
    jobUrl: "https://de.indeed.com/viewjob?jk=42c8edc200182398",
    requiredLanguages: ["Swift"],
    requiredFrameworks: [],
    isConsulting: false,
    companySize: "1,001 to 5,000",
  },
  {
    jobUrl: "https://de.indeed.com/viewjob?jk=2cde648ab3baa98d",
    requiredLanguages: ["Go", "SQL"],
    requiredFrameworks: [],
    isConsulting: false,
    companySize: "",
  },
  {
    jobUrl: "https://de.indeed.com/viewjob?jk=3c80a74054a67db0",
    requiredLanguages: ["PHP", "SQL"],
    requiredFrameworks: [],
    isConsulting: false,
    companySize: "51 to 200",
  },
  {
    jobUrl: "https://de.indeed.com/viewjob?jk=d21b1ca1c8e7ec2d",
    requiredLanguages: ["Go", "SQL"],
    requiredFrameworks: [],
    isConsulting: false,
    companySize: "51 to 200",
  },
  {
    jobUrl: "https://de.indeed.com/viewjob?jk=52e8390cdaa6d19b",
    requiredLanguages: ["Java"],
    requiredFrameworks: [],
    isConsulting: false,
    companySize: "10,000+",
  },
  {
    jobUrl: "https://de.indeed.com/viewjob?jk=e9807482b507b9af",
    requiredLanguages: ["Go"],
    requiredFrameworks: ["React"],
    isConsulting: false,
    companySize: "51 to 200",
  },
  {
    jobUrl: "https://de.indeed.com/viewjob?jk=162f0a673eacb997",
    requiredLanguages: ["Go"],
    requiredFrameworks: ["React"],
    isConsulting: false,
    companySize: "11 to 50",
  },
  {
    jobUrl: "https://de.indeed.com/viewjob?jk=b395ad0251073d5b",
    requiredLanguages: [],
    requiredFrameworks: [],
    isConsulting: false,
    companySize: "",
  },
  {
    jobUrl: "https://de.indeed.com/viewjob?jk=3d375c87d960de3a",
    requiredLanguages: ["JavaScript", "Ruby"],
    requiredFrameworks: ["React"],
    isConsulting: false,
    companySize: "11 to 50",
  },
  {
    jobUrl: "https://de.indeed.com/viewjob?jk=1c487cfc3177b976",
    requiredLanguages: ["JavaScript"],
    requiredFrameworks: ["React"],
    isConsulting: false,
    companySize: "5,001 to 10,000",
  },
  {
    jobUrl: "https://de.indeed.com/viewjob?jk=8332e6e28a2f4d4f",
    requiredLanguages: ["C#", "JavaScript", "TypeScript"],
    requiredFrameworks: [],
    isConsulting: false,
    companySize: "201 to 500",
  },
  {
    jobUrl: "https://de.indeed.com/viewjob?jk=5b8c97a49313aa9f",
    requiredLanguages: ["Java", "SQL"],
    requiredFrameworks: [],
    isConsulting: true,
    companySize: "",
  },
  {
    jobUrl: "https://de.indeed.com/viewjob?jk=ab20ea428175de60",
    requiredLanguages: ["PHP", "JavaScript", "SQL"],
    requiredFrameworks: [],
    isConsulting: false,
    companySize: "",
  },
  {
    jobUrl: "https://de.indeed.com/viewjob?jk=6708edf5ae1f0a73",
    requiredLanguages: ["Java"],
    requiredFrameworks: [],
    isConsulting: false,
    companySize: "501 to 1,000",
  },
  {
    jobUrl: "https://de.indeed.com/viewjob?jk=1965f7f102cb26e6",
    requiredLanguages: ["TypeScript", "Python"],
    requiredFrameworks: ["React"],
    isConsulting: true,
    companySize: "",
  },
  {
    jobUrl: "https://de.indeed.com/viewjob?jk=12c2c8c527b99a7e",
    requiredLanguages: ["Python"],
    requiredFrameworks: [],
    isConsulting: false,
    companySize: "",
  },
  {
    jobUrl: "https://de.indeed.com/viewjob?jk=28a0472a6961dd72",
    requiredLanguages: ["JavaScript", "Python", "Java", "C#"],
    requiredFrameworks: [],
    isConsulting: true,
    companySize: "10,000+",
  },
  {
    jobUrl: "https://de.indeed.com/viewjob?jk=37d92baa9bc8c25f",
    requiredLanguages: ["Java", "SQL"],
    requiredFrameworks: [],
    isConsulting: false,
    companySize: "",
  },
  {
    jobUrl: "https://de.indeed.com/viewjob?jk=d0ce82b22a204bf1",
    requiredLanguages: ["Rust", "C", "C++", "Python"],
    requiredFrameworks: [],
    isConsulting: false,
    companySize: "10,000+",
  },
  {
    jobUrl: "https://de.indeed.com/viewjob?jk=2ac4c206e303ccd5",
    requiredLanguages: ["JavaScript", "TypeScript"],
    requiredFrameworks: [],
    isConsulting: false,
    companySize: "",
  },
]
